---
 - hosts: all
   tasks:
    - name: i want to run command
      ios_command:
       commands:
        - show version
        - show ip int br
        - show run
        - show clock
    
    - name: i want to ping google
      ios_ping:
       dest: 8.8.8.8
      tags:
       - ping
    
    - name: i want run some more commands
      ios_command:
       commands:
        - show ip int br
      register: output

    - name: showing normal output
      debug:
       msg: "hey my output of above command is {{output}}"

    - name: execute me plz
      debug:
       msg: "hellow world!"
      tags:
       - test
